name = "hacker-news-rss-worker"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 开发环境配置
[dev]
port = 8787
local_protocol = "http"

# 非敏感的环境变量
[vars]
HACKER_NEWS_RSS_URL = "https://news.ycombinator.com/rss"
